### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by FightMan01** [MiroslavRosenov/better-ipc#7]
Tried with the example, everything working on the bot side (server) but with client side I get no response.
Log:
```
Initiating WebSocket connection
Client connected to ws://localhost:2300
Sending playload: {'endpoint': 'get_guild_channels_new', 'data': {'data': '734466114964291766'}, 'headers': {'Authorization': 'my secret key here'}}
```
No error or anything. Using quart on the client side.

**Comment by MiroslavRosenov** [comment]
Looks like the server can't return data, listed to "on_ipc_error" to catch any errors and try to look at the DEBUG logs from the bots.

If that doesn't help, can u send the "get_guild_channels_new" function code on the discord server?
